version: 2.1
jobs:
  build-test:
    docker:
      - image: cimg/base:current
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: Build
          command: | 
            echo "Building"
            mkdir build && cd build
            cmake -S ..
            make -j $(nproc)
            cd ../
            echo "Built"
      - run:
          name: Test
          command: | 
            echo "Start Testing"
            cd build
            ctest
            echo "Testing Done"

workflows:
  build-test-workflow: 
    jobs:
      - build-test
