name: Windows

on:
  pull_request:
  push:
    branches: ['**']
    tags-ignore: ['**']  # Don't trigger on tag pushes
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.host-os }}

    strategy:
      fail-fast: false
      matrix:
        host-os: ["windows-2025", "windows-11-arm"]
        include:
        - host-os: "windows-11-arm"
          suffix: "-arm64"

    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: choco install re2c

    - name: Build ninja
      shell: bash
      run: |
        cmake -Bbuild -DCMAKE_COMPILE_WARNING_AS_ERROR=1
        cmake --build build --parallel --config Debug
        cmake --build build --parallel --config Release

    - name: Test ninja (Debug)
      run: .\ninja_test.exe
      working-directory: build/Debug

    - name: Test ninja (Release)
      run: .\ninja_test.exe
      working-directory: build/Release

    - name: Create ninja archive
      shell: bash
      run: |
        mkdir artifact
        7z a artifact/ninja-win${{ matrix.suffix }}.zip ./build/Release/ninja.exe

    # Upload ninja binary archive as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: ninja-binary-archives${{ matrix.suffix }}
        path: artifact

    - name: Upload release asset
      if: github.event.action == 'published'
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # if release exists it will edit it.
        artifactContentType: "application/zip" # if empty defaults to raw
        replacesArtifacts: true # will update existing release assets if needed.
        omitBodyDuringUpdate: true # don't edit release body when published via webui
        artifacts: ./artifact/ninja-win${{ matrix.suffix }}.zip # release asset
